name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - name: Biome (format + lint)
        run: pnpm exec biome ci .

      - name: Typecheck + Unit tests
        run: pnpm nx affected -t typecheck test --parallel=3

      - name: Build
        run: pnpm nx affected -t build --parallel=3

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: E2E
        run: pnpm nx affected -t e2e
